dist: bionic
language: python
python:
  - "3.7"
cache: pip
install:
  - 'pip install pipenv'
  - 'pipenv sync'
script:
  - 'pipenv run coverage run --source=jinete --module unittest discover tests'
after_success:
  - 'pipenv run codecov'
